# Generated by Django 6.0 on 2025-12-04 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discordwebhook',
            old_name='chave',
            new_name='url',
        ),
    ]
